# Generated by Django 5.0 on 2024-01-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beekeepers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'En activité'), ('W', 'En attente'), ('X', 'Détruite')], max_length=50)),
                ('last_status_change', models.DateField()),
                ('queen_age', models.BigIntegerField()),
                ('bee_type', models.CharField(choices=[('Abeille Noire', 'Apis Mellifera Mellifera'), ('Abeille Italienne', 'Apis Mellifera Ligustica'), ('Abeille Caucasienne', 'Apis mellifera caucasica'), ('Abeille Carnolienne', 'Apis mellifera carnica'), ('Abeille Buckfast', 'Abeille hybride'), ('Abeille Charpentière', 'Xylocope')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Beeyards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beeyard', to='HiveManagement.beekeepers')),
            ],
        ),
    ]
