# Generated by Django 5.0 on 2024-01-08 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beeyards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beeyard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'En activité'), ('W', 'En attente'), ('X', 'Détruite')], max_length=50)),
                ('last_status_change', models.DateField()),
                ('queen_age', models.BigIntegerField()),
                ('bee_type', models.CharField(choices=[('Abeille Italienne', 'Apis Mellifera Ligustica'), ('Abeille Caucasienne', 'Apis mellifera caucasica'), ('Abeille Carnolienne', 'Apis mellifera carnica'), ('Abeille Buckfast', 'Abeille hybride'), ('Abeille Charpentière', 'Xylocope')], max_length=150)),
                ('beeyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='HiveManagement.beeyards')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('Supp', 'Suppression cellules royales'), ('Check', 'Check de santé'), ('Rec', 'Récolte'), ('Dist', 'Distribution de sirop'), ('Pose', 'Pose des hausses'), ('Dest', 'Destruction'), ('Multi', "Multiplication artificielle de l'essaim"), ('Trai', 'Traitement')])),
                ('date', models.DateField()),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='HiveManagement.hives')),
            ],
        ),
    ]
