# Generated by Django 5.0 on 2024-01-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='decease',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='harvest_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='is_sick',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hives',
            name='status',
            field=models.CharField(choices=[('En activité', 'A'), ('En attente', 'W'), ('Détruite', 'X')], max_length=50),
        ),
    ]
