# Generated by Django 5.0 on 2024-01-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='decease',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='harvest_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='is_sick',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hives',
            name='last_status_change',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hives',
            name='status',
            field=models.CharField(choices=[('En activité', 'A'), ('En attente', 'W'), ('Détruite', 'X')], max_length=50),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
