# Generated by Django 5.0 on 2024-01-05 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beeyards',
            old_name='nom',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('Supp', 'Suppression cellules royales'), ('Check', 'Check de santé'), ('Rec', 'Récolte'), ('Dist', 'Distribution de sirop'), ('Pose', 'Pose des hausses'), ('Dest', 'Destruction'), ('Multi', "Multiplication artificielle de l'essaim"), ('Trai', 'Traitement')])),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='HiveManagement.hives')),
            ],
        ),
    ]
