# Generated by Django 5.0 on 2024-01-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveManagement', '0002_intervention_decease_intervention_harvest_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='decease',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='harvest_quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
