# Generated by Django 5.0 on 2024-01-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveManagement', '0003_alter_intervention_decease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='decease',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='harvest_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
