# Generated by Django 5.0 on 2024-01-05 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveManagement', '0003_intervention_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeyards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beeyard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Beekeepers',
        ),
    ]
