# Generated by Django 5.0 on 2024-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveManagement', '0004_alter_intervention_decease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
